apiVersion: v1
kind: Service
metadata:
  name: sgb-api-bridge
  namespace: sgb-api-bridge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sgb-api-bridge
    app.kubernetes.io/component: serve
  ports:
    - name: http
      port: 80
      targetPort: http
